default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: djello_dev

test:
  <<: *default
  database: djello_test

production:
  <<: *default
  database: djello
